version: '3'
services:
    bp_app:
      build: .
      ports:
        - "3000:3000"
      depends_on:
        - db
      volumes:
        - ./:/opt/app
        #  - "27017:27017"
    #command: npm install && npm start    
    db:
      build: db/

